package com.yx.po;

import java.io.Serializable;
import java.util.Date;

public class ReaderInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.username
     *
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.password
     *
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.number
     *
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.real_name
     *
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.sex
     *
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.birthday
     *
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.address
     *
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.tel
     *
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.email
     *
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.register_date
     *
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.reader_number
     *
     */
    private String readerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader_info
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.id
     *
     * @return the value of reader_info.id
     *
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.id
     *
     * @param id the value for reader_info.id
     *
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.username
     *
     * @return the value of reader_info.username
     *
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.username
     *
     * @param username the value for reader_info.username
     *
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.password
     *
     * @return the value of reader_info.password
     *
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.password
     *
     * @param password the value for reader_info.password
     *
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.real_name
     *
     * @return the value of reader_info.real_name
     *
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.real_name
     *
     * @param realName the value for reader_info.real_name
     *
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.sex
     *
     * @return the value of reader_info.sex
     *
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.sex
     *
     * @param sex the value for reader_info.sex
     *
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.birthday
     *
     * @return the value of reader_info.birthday
     *
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.birthday
     *
     * @param birthday the value for reader_info.birthday
     *
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.address
     *
     * @return the value of reader_info.address
     *
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.address
     *
     * @param address the value for reader_info.address
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.tel
     *
     * @return the value of reader_info.tel
     *
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.tel
     *
     * @param tel the value for reader_info.tel
     *
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.email
     *
     * @return the value of reader_info.email
     *
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.email
     *
     * @param email the value for reader_info.email
     *
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.register_date
     *
     * @return the value of reader_info.register_date
     *
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.register_date
     *
     * @param registerDate the value for reader_info.register_date
     *
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.reader_number
     *
     * @return the value of reader_info.reader_number
     *
     */
    public String getReaderNumber() {
        return readerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.reader_number
     *
     * @param readerNumber the value for reader_info.reader_number
     *
     */
    public void setReaderNumber(String readerNumber) {
        this.readerNumber = readerNumber == null ? null : readerNumber.trim();
    }
}